package com.frl.driver;

/** Generated by build.sh from supabase.properties. Do not edit. */
public final class Config {
  private Config() {}

  public static final String SUPABASE_URL = "https://mtagkpblakgcdovzqbut.supabase.co";
  public static final String SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10YWdrcGJsYWtnY2RvdnpxYnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4MzM5NzQsImV4cCI6MjEwNDQwOTk3NH0.J_cYZTiXcwYKPqBavO4bNJMziAXJYAv3fHjqd8Hu8TM";

  public static boolean configured() {
    return !SUPABASE_URL.isEmpty() && !SUPABASE_ANON_KEY.isEmpty();
  }
}
