#!/usr/bin/env bash
#
# Build the driver APK without Gradle.
#
# Gradle would pull another few hundred megabytes and a wrapper and a daemon to do what
# four SDK tools already do for an app this size. The chain is: link the manifest into an
# APK shell, compile the Java against android.jar, translate the classes to dex, put the
# dex in the shell, align it, sign it.
#
# Every path handed to a tool goes through `cygpath -m` first. These are Windows programs
# running under Git Bash: they cannot open /d/New folder (2)/… , and the project path has
# both a space and brackets in it, so this is not optional.
set -euo pipefail

SDK="${ANDROID_SDK:-D:/Android/sdk}"
BT="$SDK/build-tools/34.0.0"
PLATFORM_UNIX="$SDK/platforms/android-34/android.jar"
JDK="${JAVA_HOME:-C:/Program Files/Java/jdk-17}"
# d8 and apksigner are .bat wrappers that look up JAVA_HOME for themselves. Exporting the
# JDK this script already found means the build does not depend on the shell it is run
# from: without it, dexing fails halfway with "JAVA_HOME is not set".
export JAVA_HOME="$JDK"

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/build"
KEYSTORE="$HERE/debug.keystore"
APK="$HERE/FRLDriver.apk"

w() { cygpath -m "$1"; }

PLATFORM="$(w "$PLATFORM_UNIX")"

for f in "$BT/aapt2.exe" "$BT/d8.bat" "$BT/zipalign.exe" "$BT/apksigner.bat" "$PLATFORM_UNIX"; do
  [ -e "$f" ] || { echo "missing: $f"; exit 1; }
done

rm -rf "$OUT"
mkdir -p "$OUT/classes" "$OUT/dex" "$OUT/gen"

# A throwaway signing key. Android refuses to install an unsigned APK, but nothing here
# goes near a store, so a local debug key is the whole requirement.
if [ ! -f "$KEYSTORE" ]; then
  echo "==> making a debug signing key"
  "$JDK/bin/keytool.exe" -genkeypair -v \
    -keystore "$(w "$KEYSTORE")" -storepass android -keypass android \
    -alias frl -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=FRL Driver, OU=League, O=FRL, C=ID" >/dev/null
fi

# The Supabase project the app talks to, written into a source file at build time rather
# than typed into the source by hand. Missing is a valid state: the app still works against
# a broadcast server on the local network, and says plainly that it has no hosted project
# when somebody types an event code.
echo "==> writing Config.java"
SUPABASE_URL=""
SUPABASE_ANON_KEY=""
if [ -f "$HERE/supabase.properties" ]; then
  # shellcheck disable=SC1090
  . "$HERE/supabase.properties"
  echo "    project: ${SUPABASE_URL:-(none)}"
else
  echo "    no supabase.properties: building for local servers only"
fi
cat > "$HERE/src/com/frl/driver/Config.java" <<JAVA
package com.frl.driver;

/** Generated by build.sh from supabase.properties. Do not edit. */
public final class Config {
  private Config() {}

  public static final String SUPABASE_URL = "${SUPABASE_URL%/}";
  public static final String SUPABASE_ANON_KEY = "$SUPABASE_ANON_KEY";

  public static boolean configured() {
    return !SUPABASE_URL.isEmpty() && !SUPABASE_ANON_KEY.isEmpty();
  }
}
JAVA

# Every build gets a fresh version, so no two APKs a driver installs ever collide. Android
# treats an install as an update only when versionCode rises, and a phone silently keeps the
# older APK when two share a code — the wrong flag on a driver's screen with no clue why.
#
# versionCode must be a monotonically rising integer under 2.1e9. Seconds since 2024-01-01
# UTC gives that: it rises every second (so back-to-back manual builds never collide) and
# stays well under the ceiling until ~2092. versionName keeps the marketing base below with a
# UTC build stamp appended, so it is legible in Settings and in any "what build am I on"
# question. The manifest carries no version, so a build rewrites nothing and leaves no diff.
#
# The marketing base: bump by hand for a real release (1.0 to 1.1); the stamp after it moves
# on its own every build.
BASE_VNAME="1.0"
VCODE="$(( $(date -u +%s) - 1704067200 ))"
VNAME="$BASE_VNAME.$(date -u +%Y%m%d.%H%M%S)"
echo "==> version $VNAME (code $VCODE)"

echo "==> linking resources"
"$BT/aapt2.exe" link \
  -o "$(w "$OUT/base.apk")" \
  -I "$PLATFORM" \
  --manifest "$(w "$HERE/AndroidManifest.xml")" \
  --min-sdk-version 24 \
  --target-sdk-version 34 \
  --version-code "$VCODE" \
  --version-name "$VNAME" \
  --java "$(w "$OUT/gen")"

echo "==> compiling java"
# Class file 55 (Java 11): d8 accepts it everywhere and nothing here needs a newer level.
# The list goes in an argfile because the paths contain spaces; javac reads forward
# slashes on Windows, so `cygpath -m` output can be quoted and used as-is.
: > "$OUT/sources.txt"
while IFS= read -r f; do printf '"%s"\n' "$(w "$f")" >> "$OUT/sources.txt"; done \
  < <(find "$HERE/src" -name '*.java')

"$JDK/bin/javac.exe" \
  -source 11 -target 11 -nowarn -encoding UTF-8 \
  -classpath "$PLATFORM" \
  -d "$(w "$OUT/classes")" \
  "@$(w "$OUT/sources.txt")"

echo "==> dexing"
# No quotes here, unlike javac's argfile: d8 takes each line whole and would treat a
# leading double quote as part of the filename.
: > "$OUT/classes.txt"
while IFS= read -r f; do printf '%s\n' "$(w "$f")" >> "$OUT/classes.txt"; done \
  < <(find "$OUT/classes" -name '*.class')

# d8 asks for a gigabyte of heap by default, which a Windows machine with a small paging
# file refuses outright: the build dies mid-dex with "insufficient memory for the Java
# Runtime Environment". This app is nine classes; half a gigabyte is generous.
# UseSerialGC as well as the heap cap: G1 reserves a quarter gigabyte of address space
# up front, and on a machine with a small paging file Windows refuses that outright,
# whatever -Xmx says. The serial collector asks for nothing like it, and this build
# dexes nine classes.
JAVA_OPTS="-Xmx512m -XX:+UseSerialGC" \
"$BT/d8.bat" --lib "$PLATFORM" --min-api 24 \
  --output "$(w "$OUT/dex")" "@$(w "$OUT/classes.txt")"

echo "==> packaging"
cp "$OUT/base.apk" "$OUT/unsigned.apk"
# python rather than `jar uf`: it puts classes.dex at the archive root with no argument
# about working directories, and it is already installed.
python - "$OUT/unsigned.apk" "$OUT/dex/classes.dex" <<'PY'
import sys, zipfile
apk, dex = sys.argv[1], sys.argv[2]
with zipfile.ZipFile(apk, 'a', zipfile.ZIP_DEFLATED) as z:
    z.write(dex, 'classes.dex')
PY

"$BT/zipalign.exe" -f -p 4 "$(w "$OUT/unsigned.apk")" "$(w "$OUT/aligned.apk")"

echo "==> signing"
"$BT/apksigner.bat" sign \
  --ks "$(w "$KEYSTORE")" --ks-pass pass:android --key-pass pass:android \
  --out "$(w "$APK")" "$(w "$OUT/aligned.apk")"

"$BT/apksigner.bat" verify --print-certs "$(w "$APK")" | head -2

echo
ls -lh "$APK" | awk '{print "APK  " $5 "  " $9}'
